@catalogue @not-executed
Feature: Native parameterised presentation predicates
  Eight declarations dispatch finite fixture and helper-owned tables through dynamic subtest labels.
  These mutable model checks do not imply complete package custody or safe authoring workflow parity.

  @candidate-go-presentation-parameters-001
  Scenario: Eleven generated fixture setups preserve only their slide count across save and reopen
    Given the empty single-slide multiple-slide text-box shapes notes hidden formatted bullet table and widescreen setups
    When each is created and saved and reopened with successful required operations
    Then the reopened SlideCount equals the count read after saving
    And text shape properties notes hidden flags formatting tables and widescreen geometry are not checked here
    And original and reopened Close errors are ignored

  @candidate-go-presentation-parameters-002
  Scenario: Six native shape enums read back from newly added shapes
    Given rectangle ellipse rounded-rectangle triangle line and arrow enum rows
    When each row creates a presentation and adds its shape
    Then the helper receives a nonnil shape interface and Type equals the requested enum
    And creation errors are ignored and no save or geometry or rendering check is performed

  @candidate-go-presentation-parameters-003
  Scenario: Sixteen helper format rows compare selected in-memory getters
    Given the sixteen CommonFormatCombinations rows whose names are generated by FormatOptions.String
    When text Test and the enabled formatting properties are applied to a new run
    Then Bold and Italic equal their row booleans
    And positive FontSize nonempty FontName and nonempty Color match their supplied values
    And Underline is not read back even when the row sets it
    And repeated size font and colour labels do not imply an exhaustive combination matrix or unique source labels

  @candidate-go-presentation-parameters-004
  Scenario: Nine slide operations are checked through resulting count only
    Given rows for adding to empty or one slide adding three inserting at start or end deleting first last or middle and duplicating
    When each operation runs after creating its requested initial slides
    Then SlideCount equals the row result of one two three three three two two two and two respectively
    And ignored operation errors ordering slide identity and clone independence are not independently checked

  @candidate-go-presentation-parameters-005
  Scenario: Four paragraph alignments read back in memory
    Given left center right and justify alignment rows
    When a new text-box paragraph is assigned each row alignment
    Then Alignment equals its enum
    And no inherited layout or serialized formatting is inspected

  @candidate-go-presentation-parameters-006
  Scenario: Three bullet types read back in memory
    Given none automatic-number and character bullet rows
    When a new text-box paragraph is assigned each row bullet type
    Then BulletType equals its enum
    And no bullet glyph numbering definition or saved list markup is checked

  @candidate-go-presentation-parameters-007
  Scenario: Four text-box coordinate tuples read back exactly in memory
    Given the origin offset large and small tuples declared by positionCases
    When each tuple is passed to AddTextBox
    Then Left Top Width and Height equal all four requested integer values
    And no save rendering or complete shape identity assertion is made

  @candidate-go-presentation-parameters-008
  Scenario: Eight helper string rows use conditional substring readback
    Given empty simple spaced Unicode emoji special-character newline and tab strings from CommonStringCases
    When each is assigned to a text box and saving succeeds before reopening
    Then if the first reopened slide has any shapes its first shape text is passed to AssertContains with the expected string
    And no-shape output skips the comparison and an empty expected string makes AssertContains return without checking text
    And Open and Close errors and WantOK are not asserted and nonempty matches need not be exact equality
