// Command casefold generates the full default Unicode 15.0 folding table without
// adding a runtime dependency. Run from repository root: go run ./tools/casefold.
package main

import (
	"bufio"
	"bytes"
	"crypto/sha256"
	"fmt"
	"go/format"
	"os"
	"strconv"
	"strings"
)

func main() {
	data, err := os.ReadFile("tools/casefold/data/CaseFolding-15.0.0.txt")
	if err != nil {
		panic(err)
	}
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by go run ./tools/casefold; DO NOT EDIT.\n// Unicode 15.0.0 default full case folding; source SHA256 %x.\n// Data licence: tools/casefold/data/LICENSE.txt (Unicode License V3).\npackage document\n\nvar fullCaseFold = map[rune]string{\n", sha256.Sum256(data))
	s := bufio.NewScanner(bytes.NewReader(data))
	for s.Scan() {
		line := strings.SplitN(s.Text(), "#", 2)[0]
		if strings.TrimSpace(line) == "" {
			continue
		}
		f := strings.Split(line, ";")
		if len(f) < 3 {
			panic("malformed casefold row")
		}
		status := strings.TrimSpace(f[1])
		if status != "C" && status != "F" {
			continue
		}
		code, err := strconv.ParseUint(strings.TrimSpace(f[0]), 16, 32)
		if err != nil {
			panic(err)
		}
		var mapped []rune
		for _, h := range strings.Fields(f[2]) {
			r, err := strconv.ParseUint(h, 16, 32)
			if err != nil {
				panic(err)
			}
			mapped = append(mapped, rune(r))
		}
		fmt.Fprintf(&b, "0x%X:%q,\n", code, string(mapped))
	}
	if err = s.Err(); err != nil {
		panic(err)
	}
	b.WriteString("}\n")
	out, err := format.Source(b.Bytes())
	if err != nil {
		panic(err)
	}
	if err = os.WriteFile("pkg/document/casefold_generated.go", out, 0644); err != nil {
		panic(err)
	}
}
